### ISSUE TITLE
foodRepository variable in StartUp.cs

### ISSUE THREAD

**Issue by pmareke** [FabianGosebrink/ASPNETCore-WebAPI-Sample#3]
Why are you creating but not using this variable?

`123 var foodRepository = app.ApplicationServices.GetRequiredService<IFoodRepository>();`

Awesome work, thanks for sharing!

**Comment by FabianGosebrink** [comment]
This line was a relict from the past. It is removed with the latest checkin. Thank you for pointing this out!
