### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by veonua** [FabianGosebrink/ASPNETCore-WebAPI-Sample#8]
An unhandled exception occurred while processing the request.
InvalidOperationException: The constraint reference 'string' could not be resolved to a type. Register the constraint type with 'Microsoft.AspNetCore.Routing.RouteOptions.ConstraintMap'.
Microsoft.AspNetCore.Routing.DefaultParameterPolicyFactory.Create(RoutePatternParameterPart parameter, string inlineText)

**Comment by FabianGosebrink** [comment]
Hey @veonua ,

please give more information. When d you get this? Is this fixed in the meantime?

thanks

**Comment by veonua** [comment]
I believe this was due of Core 3 code in Core 2 environment. But this should be handled by compiler , not throwing Runtime errors

**Comment by FabianGosebrink** [comment]
Hey @veonua ,

thanks for your message. Again: When do you get the error? I have to reproduce it to be able to fix it :) Generally: Do you still get it?

Thanks

**Comment by veonua** [comment]
I got this error month ago, I do not store code with an error for a such long time. Probably you can try to check stack trace from the first message and do not throw Runtime exceptions ever

**Comment by FabianGosebrink** [comment]
Hey @veonua, thanks for your message. I think the error is done now. If it comes up again please leave another issue. Thanks for reporting and responding so fast. 👍
